# Generated by Django 4.0.4 on 2022-06-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=40)),
                ('surname_admin', models.CharField(max_length=40)),
                ('telephone_numb', models.DecimalField(decimal_places=0, max_digits=11)),
                ('url_vk', models.CharField(max_length=30)),
                ('admin_photo', models.ImageField(upload_to='photos/adm')),
            ],
            options={
                'verbose_name': 'Администраторы',
                'verbose_name_plural': 'Администратор',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=8, verbose_name='Учебный год')),
                ('year_start', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='С')),
                ('year_end', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='По')),
                ('url_photo', models.CharField(max_length=30, verbose_name='Адрес архива с фото')),
                ('url_video', models.CharField(max_length=30, verbose_name='Адрес архива с видео')),
                ('arch_photo', models.ImageField(upload_to='photos/arch/%Y', verbose_name='Фото')),
                ('arch_video', models.ImageField(upload_to='photos/arch/%Y', verbose_name='Фото видео')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=40, verbose_name='Мероприятие')),
                ('content', models.TextField(verbose_name='Контент')),
                ('photo', models.ImageField(upload_to='photos/events', verbose_name='Фото')),
                ('is_Published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('guest_surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('guest_part', models.CharField(max_length=40, null=True, verbose_name='Отчество')),
                ('event', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='Мероприятие')),
                ('id_part_year', models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.CreateModel(
            name='Nominations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination', models.CharField(max_length=60, verbose_name='Номинация')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.event')),
            ],
            options={
                'verbose_name': 'Номинация',
                'verbose_name_plural': 'Номинации',
            },
        ),
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resid_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('resid_surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('birth_date', models.DateTimeField(verbose_name='Дата рождения')),
                ('login', models.CharField(max_length=40, verbose_name='Логин')),
                ('password', models.CharField(max_length=60, verbose_name='Пароль')),
                ('administrator', models.BooleanField(default=False, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участник',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.event')),
                ('id_nomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.nominations')),
                ('id_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.residents')),
                ('id_part_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.archive')),
            ],
            options={
                'verbose_name': 'Победитель',
                'verbose_name_plural': 'Победители',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.event')),
                ('id_part_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.archive')),
                ('id_resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.residents')),
            ],
            options={
                'verbose_name': 'Участники',
                'verbose_name_plural': 'Участник',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('new', models.TextField(verbose_name='Содержание')),
                ('photo_n', models.ImageField(upload_to='')),
                ('url', models.CharField(max_length=40, verbose_name='Доп ссылка')),
                ('for_guests', models.BooleanField(default=True, verbose_name='Доступ гостям')),
                ('id_part_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.archive')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.UniqueConstraint(fields=('id_resident', 'event', 'id_part_year'), name='unique_participation'),
        ),
    ]
