# Generated by Django 4.0.4 on 2022-06-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.event'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='id_part_year',
            field=models.ForeignKey(default=20202021, on_delete=django.db.models.deletion.PROTECT, to='main.archive'),
        ),
    ]
